### ISSUE TITLE
Latest `@octokit/auth-app` not compatible with `octokit-auth-probot`

### ISSUE THREAD

**Issue by bcoe** [probot/octokit-auth-probot#120]
I'm getting the following compilation error when I attempt to update the dependencies of a library that uses `octokit-auth-probot`:

```shell
node_modules/octokit-auth-probot/dist-types/types.d.ts:14:75 - error TS2694: Namespace '"/Users/bencoe/google/repo-automation-bots/packages/gcf-utils/node_modules/@octokit/auth-app/dist-types/index"' has no exported member 'AuthOptions'.

14 export declare type AuthOptions = TokenAuthTypes["AuthOptions"] | AppAuth.AuthOptions | {
```

**Comment by bcoe** [comment]
The culprit seems to be [this pr](https://github.com/octokit/auth-app.js/pull/283).

**Comment by gr2m** [comment]
Thanks Ben I'll look into it

**Comment by bcoe** [comment]
@gr2m thank you \o/

**Comment by gr2m** [comment]
Should be good now. I've also added `npm run build` to the test ci so we shouldn't miss that in future

**Comment by bcoe** [comment]
Thank you @gr2m.
