### ISSUE TITLE
Create maintenance release of 1.x

### ISSUE THREAD

**Issue by wolfy1339** [probot/octokit-auth-probot#266]
Looking through the changes in Probot that made the tests start failing, I noticed that this package upgraded several Octokit packages to versions incompatible with others already in Probot. Leading to duplication and possibly errors

The commits contained in the releases 1.2.7, 1.2.8 and 1.2.9 should be reverted

**Comment by wolfy1339** [comment]
The indirect dependency on `jsonwebtoken` was upgraded to v9 which dropped support for NodeJS v10

**Comment by gr2m** [comment]
I created [`1.x`](https://github.com/probot/octokit-auth-probot/tree/1.x)
