### ISSUE TITLE
Publishing fails

### ISSUE THREAD

**Issue by AaronDewes** [probot/octokit-auth-probot#275]
![grafik](https://github.com/probot/octokit-auth-probot/assets/67546953/a78ac4f7-3ed7-451d-ae31-1d43d8fc4b5c)

The errors seem to indicate `PROBOTBOT_NPM_TOKEN` expired.

@gr2m Please check this and update the secret. I'm currently trying to update to the latest Octokit, ESM and use `@octokit/app`, and this would help a lot.

**Comment by gr2m** [comment]
updated the token. I enabled 2FA on the npm account and had to generate an automation token to use for release automation
